add compat for core refactoring
rpkilby/tox-venv pull request #14
Opened 2018-04-14 16:59 UTC by obestwalter

Added a simple import compat layer - mainly for local development and tests - this can be removed once changes in core are merged.

2018-04-14 19:18 UTC, rpkilby requested changes

2018-04-14 19:18 UTC, rpkilby commented on tests/test_z_cmdline.py
> +            from tox import _exit_code_str as exit_code_str
Should this occur before the `if exit_code` block? `exit_code_str` is not defined if entering the else block.

2018-04-14 19:27 UTC, rpkilby commented
Hi @obestwalter - I'm not following entirely. I assume this compat is related to the spring cleaning PR? And I'm assuming that the end state would be that `tox._exit_code_str` is being moved to the public API as `tox.exit_code_str`?

Do you need these changes merged for your own testing purposes, or is this just keeping tox-venv's test suite up-to-date? If it's the latter, I usually just update the tests once a new version of tox is released.

2018-04-14 19:45 UTC, rpkilby commented
Also, looking at the spring cleaning PR, should this be `tox.exc.exit_cod_str`?

2018-04-14 21:25 UTC, obestwalter commented
Hi @rpkilby - sorry for not referencing that here. It's mainly for local dev, to work with different versions of of tox until it's moved over. Not even strictly necessary, but handy in the meantime?

2018-04-14 21:48 UTC, rpkilby commented
That makes sense. I'll review once the test is fixed up.

2018-04-14 22:03 UTC, obestwalter commented
whoops, that was a silly one :)

2018-06-01 19:00 UTC, rpkilby commented
Hi @obestwalter. Do you need these changes merged, or is it sufficient if they live on a branch?

2018-06-02 22:39 UTC, obestwalter commented
Ho @rpkilby - changes in core are merged, so no need any more for this I think :)

2018-06-03 23:21 UTC, closed without merging